version: '3'
services:
  app:
    build:
      context: ./apl
      dockerfile: dockerfile
    volumes:
      - ./apl/php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    ports:
      - "8000:80"
    tty: true
    links:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=test
      - PMA_PASSWORD=test
    links:
      - mysql
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
volumes:
  mysql: